<a href="https://colab.research.google.com/github/anitha6752/Anudip/blob/main/day16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#numpy
#array module

In [2]:
from array import array
my_array=('i',[2,5,7,8,6])

In [3]:
my_array

('i', [2, 5, 7, 8, 6])

In [4]:
type(my_array)

tuple

In [5]:
#numpy arrays

In [6]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5])

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.ndim

1

In [11]:
arr.dtype

dtype('int64')

In [12]:
array_new = np.array([1,2,3,4,5])

In [13]:
array_new +3

array([4, 5, 6, 7, 8])

In [14]:
type(array_new)

numpy.ndarray

In [15]:
my_numpy_array=np.array([1,2,3,4,5])

In [16]:
new_array=my_numpy_array*3

In [17]:
new_array

array([ 3,  6,  9, 12, 15])

In [18]:
type(new_array)

numpy.ndarray

In [19]:
type(my_numpy_array)

numpy.ndarray

In [20]:
new_array>5

array([False,  True,  True,  True,  True])

In [22]:
matrix=np.array([
    [1,2,3],
    [4,3,5],
    [3,7,9]])

In [23]:
matrix

array([[1, 2, 3],
       [4, 3, 5],
       [3, 7, 9]])

In [24]:
arr_2d=np.array([[0,1,2],[3,4,5],[7,9,8]])

In [25]:
arr_2d*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [14, 18, 16]])

In [26]:
type(arr_2d)

numpy.ndarray

In [27]:
arr_2d.ndim

2

In [28]:

arr_2d+2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 9, 11, 10]])

In [29]:
arr_2d-1

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 6,  8,  7]])

In [30]:
arr_2d%2

array([[0, 1, 0],
       [1, 0, 1],
       [1, 1, 0]])

In [31]:
list_data = [1,6,5,7,9]
array_from_list=np.array(list_data)

In [32]:
list_data

[1, 6, 5, 7, 9]

In [33]:
type(list_data)

list

In [34]:
array_from_list

array([1, 6, 5, 7, 9])

In [35]:

type(array_from_list)

numpy.ndarray

In [36]:
array_from_list

array([1, 6, 5, 7, 9])