<a href="https://colab.research.google.com/github/anitha6752/Anudip/blob/main/day17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#creating numpy array
import numpy as np
a= np.ones((3,4))
type(a)

numpy.ndarray

In [2]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
a1=np.zeros((2,4))
a1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
zeros_array=np.zeros((3,3))
ones_array=np.ones((2,4))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:

ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
identity_matrix=np.eye(3)

In [7]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
b=[1,2,3,4]

In [9]:
int_array=np.array([1,2,3], dtype=np.int32)
float_array=np.array([0.1,0.2,0.3],dtype=np.float64)

In [13]:
float_array

array([0.1, 0.2, 0.3])

In [14]:
a2=np.arange(0,8)

In [15]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
linspace_array=np.linspace(0,10,6)

In [17]:
linspace_array

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [18]:
linspace_array1=np.linspace(0,20,5)

In [19]:
linspace_array1

array([ 0.,  5., 10., 15., 20.])

In [20]:
random_array=np.random.rand(4,4)

In [21]:
random_array

array([[0.74003974, 0.47152891, 0.80833752, 0.07046538],
       [0.13250242, 0.20958701, 0.66414733, 0.05638865],
       [0.22798452, 0.4023028 , 0.35987944, 0.97707208],
       [0.98673003, 0.639789  , 0.63119323, 0.21648425]])

In [22]:
#basic indexing
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


In [23]:
arr1=np.array([[23,4,6,3],[1,67,98,6]])
arr1


array([[23,  4,  6,  3],
       [ 1, 67, 98,  6]])

In [24]:
print(arr1[0,3])


3


In [26]:
print(arr1[1,-1])

6


In [25]:
#1D array slicing
arr2=np.array([1,7,8,5,4,3])
print(arr2[1:4])
print(arr2[:6])
print(arr2[:-1])

[7 8 5]
[1 7 8 5 4 3]
[1 7 8 5 4]


In [27]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix[0:1,1:3])

[[2 3]]


In [28]:
print(matrix[2:3,1:2])

[[8]]


In [29]:
print(matrix[1:2,1:3])

[[5 6]]


In [30]:

v=np.array([1,2,3,4])

In [31]:
s=v[1:3]
s

array([2, 3])

In [32]:
#copy
a=np.array([1,2,3,4,5])
b=a[1:3].copy()
b

array([2, 3])

In [33]:
#shape
arr=np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [34]:
a=np.arange(12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
d=np.arange(20)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
e=d.reshape(5,4)
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [38]:
arr_3d=np.array([[0,1,2],
              [4,5,6],
              [7,8,9]])
arr_3d.transpose()

array([[0, 4, 7],
       [1, 5, 8],
       [2, 6, 9]])

In [39]:
arr=np.array([[1,2,3,4,5,6],[10,20,30,40,50,60]])
arr.transpose()


array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50],
       [ 6, 60]])