<a href="https://colab.research.google.com/github/anitha6752/Anudip/blob/main/day18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
uniform=np.random.rand(3,3)
print("Uniform Distridution:\n",uniform)


Uniform Distridution:
 [[0.96052189 0.4103198  0.019949  ]
 [0.99405113 0.78166764 0.01376891]
 [0.0573812  0.58536197 0.75185906]]


In [2]:
#searching in array where----returns the index value
a=np.array([1,2,3,4,5])
np.where(a>3)

(array([3, 4]),)

In [3]:
np.where(a>4)

(array([4]),)

In [4]:
np.where(a<2)

(array([0]),)

In [5]:
np.argmax(a)


np.int64(4)

In [6]:
np.argmin(a)

np.int64(0)

In [7]:
#searchsorted
sorted_arr=np.array([1,3,5,7])
np.searchsorted(sorted_arr,6)

np.int64(3)

In [8]:
np.searchsorted(sorted_arr,4)

np.int64(2)

In [9]:
#extract --- retuns the value
np.extract(a>3,a)

array([4, 5])

In [10]:
#transpose
matrix=([[1,2,3],[4,5,6]])
matrix

[[1, 2, 3], [4, 5, 6]]

In [11]:
np.transpose(matrix)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
#mean
print("Mean Value",np.mean(a))

Mean Value 3.0


In [13]:
#splitting arrays
#--equal parts split
aa=np.array([1,2,3,4,5,6])
np.split(aa,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [14]:
np.split(aa,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [15]:
#--split at specific positions
np.split(aa,[2,4])

[array([1, 2]), array([3, 4]), array([5, 6])]

In [16]:
#matrix
mat=np.array([[1,2,3],
              [4,5,6]])
np.split(mat, 3,axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [17]:
matr=np.array([[1,2,3,4],
              [5,6,7,8]])
np.split(matr,2,axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [18]:
matr=np.array([[1,2,3,4],
              [5,6,7,8]])
np.split(matr,2,axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [19]:
matt=np.array([[3,1,2],
               [6,5,4]])
print("sorted rows:\n",np.sort(matt,axis=1))

sorted rows:
 [[1 2 3]
 [4 5 6]]


In [20]:
print("sorted columns:\n",np.sort(matt,axis=0))

sorted columns:
 [[3 1 2]
 [6 5 4]]
